name: camera_android_camerax
description: Android implementation of the camera plugin using the CameraX library.
repository: https://github.com/flutter/plugins/tree/main/packages/camera/camera_android_camerax
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: camera
    platforms:
      android:
        package: io.flutter.plugins.camerax
        pluginClass: CameraAndroidCameraxPlugin
        dartPluginClass: AndroidCameraCameraX

dependencies:
  camera_platform_interface: ^2.2.0
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  simple_ast:
    git:
      url: git@github.com:bparrishMines/penguin.git
      path: packages/simple_ast
  stream_transform: ^2.1.0

dev_dependencies:
  async: ^2.5.0
  build_runner: ^2.2.0
  code_template_processor:
    git:
      url: git@github.com:bparrishMines/penguin.git
      path: packages/code_template_processor
  flutter_test:
    sdk: flutter
  gen_api_impls:
    git:
      url: git@github.com:bparrishMines/penguin.git
      path: packages/gen_api_impls
  mockito: ^5.3.2
  pigeon: ^9.0.0
  simple_ast_generator:
    git:
      url: git@github.com:bparrishMines/penguin.git
      path: packages/simple_ast_generator